version: '3.8'

services:
  traderforecast-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: traderforecast
      POSTGRES_PASSWORD: traderforecast
    ports:
      - '5432:5432'
      - '6543:6543'
    volumes:
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traderforecast

volumes:
  docker-nest-postgres:

networks:
  traderforecast: null

